name: Lint

on:
    push:
        branches:
            ["main"]
            # Allows you to run this workflow manually from the Actions tab
        workflow_dispatch:

jobs:
    # Disabled due to badge checker
    # awesome-lint:
    #     runs-on: ubuntu-latest

    #     steps:
    #         - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
    #         - name: Use Node.js
    #           uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
    #           with:
    #               node-version: lts/*
    #         - name: Run awesome-lint
    #           run: npx awesome-lint
    broken-links-checker:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
            - name: Use Node.js
              uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
              with:
                  node-version: lts/*
            - name: Run markdown-link-check
              run: npx markdown-link-check@3.14.2 README.md
